spring:
  cloud:
    gateway:
      routes:
      - id: msvc-users
        uri: lb://msvc-users
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - id: msvc-oauth
        uri: lb://msvc-oauth
        predicates:
        - Path=/api/security/**
        filters:
        - StripPrefix=2
      
          